
import {StyleSheet, Platform} from 'react-native';
import {dimens, fontsizes} from '../../constants/dimens';

import {useTheme} from '@react-navigation/native';
import React from 'react';
import font from '../../constants/fonts';

const getStyles = props =>
  StyleSheet.create({
    elapsedTime: {
      fontSizes: fontsizes.FONT_14Px_H6,
      fontFamily: font.Proximanovacond_Medium,
      color: props.colors.textInputTextColor,
    },
    timerStyle: {
      fontFamily: font.ProximaNovaExtraCondensed_Bold,
      fontSize: fontsizes.FONT_48Px_,
      color: props.colors.bigTextColors,
    },
    targetText: {
      fontsizes: fontsizes.FONT_14Px_H6,
      fontFamily: font.Proximanovacond_Medium,
      color: props.colors.smallTextColors,
    },
    endTaskBtn: {
      width: dimens.w30,
      height: dimens.h4,
      backgroundColor: props.colors.pinkBg,
      borderRadius: dimens.h10,
      alignItems: 'center',
      justifyContent: 'space-evenly',
      flexDirection: 'row',
      marginTop: dimens.h1,
      // opacity:0.3
    },
    whiteContainer: {
      // width: dimens.w90,
      // backgroundColor: props.colors.white,
      backgroundColor: 'transparent',
      alignItems: 'center',
      borderRadius: dimens.h1,
    },
    whiteContainerTimer: {
      // width: dimens.w90,
      backgroundColor: props.colors.white,
      alignItems: 'center',
      borderRadius: dimens.h2,
      elevation: 5,
      shadowColor: props.colors.black,
      shadowOffset: {width: 2, height: 2},
      shadowOpacity: 0.3,
    },
    endFastText: {
      fontSizes: fontsizes.FONT_12Px_H6,
      fontFamily: font.Proximanova_Bold,
      color: props.colors.deepmagenta,
    },
    roundBtn: {
      position: 'absolute',
      backgroundColor: props.colors.lightblue,
      left: dimens.h1,
      borderRadius: dimens.w6,
      height: dimens.w12,
      width: dimens.w12,
      justifyContent: 'center',
      alignItems: 'center',
      // padding: dimens.h2,
      top: dimens.h1,
      zIndex: 11,
    },
    roundBtnRight: {
      position: 'absolute',
      backgroundColor: props.colors.pinkBg,
      right: dimens.h1,
      borderRadius: dimens.w6,
      height: dimens.w12,
      width: dimens.w12,
      justifyContent: 'center',
      alignItems: 'center',
      // padding: dimens.h2,
      top: dimens.h1,
      zIndex: 11,
    },

    fastingHourstext: {
      fontsizes: fontsizes.FONT_12Px_H6,
      fontFamily: font.Proximanova_Bold,
      color: props.colors.deepmagenta,
      includeFontPadding: false,
    },
    separator: {
      height: dimens.h5,
      width: dimens.wo4,
      marginBottom: dimens.h2,
      // flex: 1,
      // width:dimens.w20,
      backgroundColor: props.colors.separatorColor,
    },
    separator2: {
      height: dimens.h5,
      // width: dimens.wo4,
      marginBottom: dimens.h2,
      // flex: 1,
      // width:dimens.w20,
      backgroundColor: props.colors.separatorColor,
    },
    timerStartedTime: {
      // alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: dimens.w4_5,
    },
    timerStartedTimeText: {
      fontSize: fontsizes.FONT_14PX,
      fontFamily: font.Proximanovaexcn_Regular,
      color: props.colors.textInputTextColor,
      includeFontPadding: false,
      fontWeight: '700',
    },
    timerStarted: {
      fontSize: fontsizes.FONT_16PX,
      fontFamily: font.Proximanovaexcn_Regular,
      color: props.colors.bigTextColors,
      includeFontPadding: false,
      fontWeight: '700',
    },
    upcomingUIContainer: {
      // height: dimens.h20,
      backgroundColor: props.colors.white,
      // backgroundColor: 'pink',
      borderRadius: dimens.h2,
      // marginVertical: dimens.h2,
      marginTop: dimens.h2,
      padding: dimens.w4,
      shadowColor: props.colors.black,
      shadowOffset: {width: 2, height: 2},
      shadowOpacity: 0.3,
      // shadowRadius: 3,
      elevation: 5,
      marginHorizontal: 1,
    },
    upcomingTitle: {
      fontSize: fontsizes.FONT_20Px_H5,
      fontFamily: font.ProximaNovaExtraCondensed_Bold,
      color: props.colors.black,
      marginTop: dimens.h1,
    },
    upcomingpara: {
      fontSizes: fontsizes.FONT_12Px_H6,
      fontFamily: font.Proximanovaexcn_Regular,
      color: props.colors.black,
      marginVertical: dimens.h1,
    },
    titleStylebtnBlack: {
      color: props.colors.black,
      fontSize: fontsizes.FONT_14Px_H6,
      fontFamily: font.Proximanova_Bold,
      textAlign: 'center',
    },
    containerBtnWhite: {
      // backgroundColor: props.colors.grayBtnBg,
      // // backgroundColor: 'red',
      width: dimens.w30,
      height: dimens.h5,
      borderRadius: dimens.h10,
      // alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    titleStylebtnrevser: {
      color: props.colors.graditnBtnTextColorReverse,
      fontSize: fontsizes.FONT_14Px_H6,
      fontFamily: font.Proximanova_Bold,
      textAlign: 'center',
    },
    gradStylesWhite: {
      borderRadius: dimens.h10,
      // width: dimens.w86_1,
      // height: dimens.h5_4,
      backgroundColor: props.colors.grayBtnBg,
    },
    gradStyles: {
      borderRadius: dimens.h10,
      width: dimens.w87_3,
      height: dimens.h5_7,
    },
    containerBtnWhiteWithmargin: {
      // backgroundColor: props.colors.grayBtnBg,
      width: dimens.w30,
      height: dimens.h5,
      borderRadius: dimens.h10,
      // alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginStart: dimens.w2,
    },
    count: {
      color: props.colors.bigTextColors,
      fontSize: fontsizes.FONT_32Px_H2,
      fontWeight: '500',
      fontFamily: font.ProximaNovaExtraCondensed_Bold,
    },
    waterIntakeBtntext: {
      color: props.colors.bigTextColors,
      fontSize: fontsizes.FONT_28Px_H3,
      fontFamily: font.ProximaNovaExtraCondensed_Bold,
    },
    waterIntakeBtntext2: {
      color: props.colors.bigTextColors,
      fontSize: fontsizes.FONT_16Px_,
      fontFamily: font.Proximanovaexcn_Regular,
    },
    waterIntakeBtnTochable: {
      backgroundColor: props.colors.white,
      borderRadius: dimens.h1,
      flex: 1,
      // flex: 2 / 1,
      // marginEnd: dimens.w4,
      flexDirection: 'row',
      // alignItems: 'baseline',
      paddingTop: dimens.h2,
      shadowColor: '#000',
      shadowOffset: {width: 1, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 8,
      // height: dimens.h13,
      // width: dimens.w44,
      marginRight: 8,
      paddingBottom: 10,
    },
    waterIntakeBtnTochable2: {
      backgroundColor: props.colors.white,
      borderRadius: dimens.h1,
      flex: 1,
      // flex: 2 / 1,
      flexDirection: 'row',
      // alignItems: 'baseline',
      paddingTop: dimens.h2,
      shadowColor: '#000',
      shadowOffset: {width: 1, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 8,
      // height: dimens.h13,
      // width: dimens.w44,
      marginLeft: 8,
      paddingBottom: 10,
    },
    dailyArtTitle: {
      color: props.colors.calenderText,
      fontSize: fontsizes.FONT_24Px_H4,
      fontFamily: font.ProximaNovaExtraCondensed_Bold,
      marginBottom: dimens.h2,
    },
    cardsRowContainer: {flexDirection: 'row', justifyContent: 'space-between'},
    waterCardContainer: {
      backgroundColor: '#fff',
      flex: 1,
      flexDirection: 'row',
      marginRight: dimens.w2,
      padding: dimens.h1_5,
      // elevation: 4,
      borderRadius: dimens.h2,
      elevation: 5,
      shadowColor: props.colors.black,
      shadowOffset: {width: 2, height: 2},
      shadowOpacity: 0.3,
    },
    waterLevelContainer: {flex: 2, justifyContent: 'flex-end'},
    activityCardContainer: {
      backgroundColor: '#fff',
      flex: 1,
      flexDirection: 'row',
      marginLeft: dimens.w2,
      // elevation: 4,
      padding: dimens.h1_5,
      
      borderRadius: dimens.h2,
      elevation: 5,
      shadowColor: props.colors.black,
      shadowOffset: {width: 2, height: 2},
      shadowOpacity: 0.3,
    },
    activityLevelContainer: {flex: 2, justifyContent: 'flex-end'},
    titleStylebtn: {
      color: props.colors.graditnBtnTextColor,
      fontSize: fontsizes.FONT_18Px_,
      fontFamily: font.Proximanova_Bold,
    },
    containerBtn: {
      alignSelf: 'center',
    },
  });

function useStyles() {
  const {colors} = useTheme();
  // We only want to recompute the stylesheet on changes in color.
  const styles = React.useMemo(() => getStyles({colors}), [colors]);
  return styles;
}

export default useStyles;
